# Generated by Django 4.1.9 on 2023-10-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_friendship"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="friendship",
            constraint=models.UniqueConstraint(fields=("follower", "followee"), name="unique_follow"),
        ),
    ]
